<?php

declare(strict_types=1);

namespace Finkok\CfdiBundle\DependencyInjection;

use Finkok\CfdiBundle\Config\Environment;
use Finkok\CfdiBundle\Config\Service;
use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

/**
 * Árbol de configuración del bundle (clave raíz `finkok`).
 */
final class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('finkok');
        $root = $treeBuilder->getRootNode();

        $root
            ->info('Web Services de Finkok para timbrado y cancelación de CFDI.')
            ->children()
                ->scalarNode('default_profile')
                    ->defaultNull()
                    ->info('Perfil usado cuando una llamada no indica uno explícitamente.')
                    ->example('matriz')
                ->end()
                ->arrayNode('profiles')
                    ->info('Perfiles de credenciales; permite operar varios RFC emisores desde la misma aplicación.')
                    ->useAttributeAsKey('name')
                    ->requiresAtLeastOneElement()
                    ->arrayPrototype()
                        ->children()
                            ->scalarNode('username')
                                ->isRequired()
                                ->cannotBeEmpty()
                                ->info('Usuario del panel de Finkok.')
                            ->end()
                            ->scalarNode('password')
                                ->isRequired()
                                ->cannotBeEmpty()
                                ->info('Contraseña del panel de Finkok.')
                            ->end()
                            ->scalarNode('taxpayer_id')
                                ->defaultNull()
                                ->info('RFC del emisor. Obligatorio para cancelar; opcional para timbrar.')
                                ->example('EKU9003173C9')
                            ->end()
                            ->enumNode('environment')
                                ->values(array_map(static fn (Environment $case): string => $case->value, Environment::cases()))
                                ->defaultValue(Environment::Demo->value)
                                ->info('Ambiente de Finkok al que apunta el perfil.')
                            ->end()
                            ->scalarNode('certificate')
                                ->defaultNull()
                                ->info('Ruta al archivo .cer o su contenido en PEM. Opcional: solo se usa al cancelar.')
                            ->end()
                            ->scalarNode('private_key')
                                ->defaultNull()
                                ->info('Ruta al archivo .key o su contenido en PEM. Opcional: solo se usa al cancelar.')
                            ->end()
                            ->scalarNode('private_key_passphrase')
                                ->defaultNull()
                                ->info('Contraseña propia de la llave privada, si el codificador CSD la necesita.')
                            ->end()
                            ->arrayNode('endpoints')
                                ->info('Sobrescritura de URLs para este perfil (por ejemplo si un emisor usa otro host).')
                                ->useAttributeAsKey('service')
                                ->arrayPrototype()
                                    ->children()
                                        ->scalarNode('demo')->defaultNull()->end()
                                        ->scalarNode('production')->defaultNull()->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                        ->validate()
                            ->ifTrue(static fn (array $profile): bool => (null === $profile['certificate']) !== (null === $profile['private_key']))
                            ->thenInvalid('El perfil debe definir "certificate" y "private_key" juntos, o ninguno de los dos. Valor recibido: %s')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('endpoints')
                    ->info('URLs de los servicios. Los valores por defecto apuntan a los hosts oficiales de Finkok.')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode(Service::Stamp->value)
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('demo')->defaultValue(Service::Stamp->defaultEndpoint(Environment::Demo))->end()
                                ->scalarNode('production')->defaultValue(Service::Stamp->defaultEndpoint(Environment::Production))->end()
                            ->end()
                        ->end()
                        ->arrayNode(Service::Cancel->value)
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('demo')->defaultValue(Service::Cancel->defaultEndpoint(Environment::Demo))->end()
                                ->scalarNode('production')->defaultValue(Service::Cancel->defaultEndpoint(Environment::Production))->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('http')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->floatNode('timeout')
                            ->defaultValue(30.0)
                            ->min(0)
                            ->info('Tiempo máximo, en segundos, de cada petición al Web Service.')
                        ->end()
                        ->booleanNode('log_payloads')
                            ->defaultFalse()
                            ->info('Escribe el envelope completo en el log. No lo actives en producción: contiene datos fiscales y CSD.')
                        ->end()
                        ->scalarNode('user_agent')
                            ->defaultValue('finkok-cfdi-bundle/1.0')
                        ->end()
                        ->arrayNode('retry')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')
                                    ->defaultTrue()
                                    ->info('Reintenta errores de transporte y códigos transitorios. Es seguro porque Finkok deduplica por UUID.')
                                ->end()
                                ->integerNode('max_retries')->defaultValue(2)->min(0)->max(10)->end()
                                ->integerNode('delay_ms')->defaultValue(500)->min(0)->end()
                                ->floatNode('multiplier')->defaultValue(2.0)->min(1.0)->end()
                                ->integerNode('max_delay_ms')->defaultValue(0)->min(0)->end()
                                ->floatNode('jitter')->defaultValue(0.1)->min(0.0)->max(1.0)->end()
                                ->arrayNode('http_codes')
                                    ->info('Códigos que disparan reintento; 0 representa un error de transporte.')
                                    ->integerPrototype()->end()
                                    ->defaultValue([0, 429, 500, 502, 503, 504])
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('preflight')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultTrue()
                            ->info('Valida el CFDI en local antes de enviarlo, evitando incidencias 301/705 y el límite de 1 MB.')
                        ->end()
                        ->booleanNode('require_signature')
                            ->defaultTrue()
                            ->info('Exige el atributo Sello en el comprobante; sin él Finkok responde CFDI40102.')
                        ->end()
                    ->end()
                ->end()
            ->end()
            ->validate()
                ->ifTrue(static fn (array $config): bool => null !== $config['default_profile']
                    && !isset($config['profiles'][$config['default_profile']]))
                ->thenInvalid('El valor de "default_profile" debe existir dentro de "profiles". Valor recibido: %s')
            ->end();

        return $treeBuilder;
    }
}
